# Generated by Django 5.1.1 on 2024-09-12 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=200)),
                ('clinic_logo', models.ImageField(upload_to='clinic_logos/')),
                ('physician_name', models.CharField(max_length=200)),
                ('physician_contact', models.CharField(max_length=200)),
                ('patient_first_name', models.CharField(max_length=200)),
                ('patient_last_name', models.CharField(max_length=200)),
                ('patient_dob', models.DateField()),
                ('patient_contact', models.CharField(max_length=200)),
                ('chief_complaint', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('consultation_note', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)])),
            ],
        ),
    ]
