# Generated by Django 5.1.1 on 2024-09-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_alter_consultation_clinic_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='clinic_logo',
            field=models.ImageField(upload_to='clinic_logos/'),
        ),
    ]
