# Generated by Django 5.1.1 on 2024-09-12 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_consultation_clinic_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient_contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with 10 to 15 digits.', regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='physician_contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with 10 to 15 digits.', regex='^\\d{10,15}$')]),
        ),
    ]
