# Generated by Django 5.1.1 on 2024-09-12 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_alter_consultation_patient_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient_contact',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian phone number with 10 digits or include country code +91.', regex='^\\+91\\d{10}$|^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='physician_contact',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian phone number with 10 digits or include country code +91.', regex='^\\+91\\d{10}$|^\\d{10}$')]),
        ),
    ]
