# Generated by Django 5.1.1 on 2024-09-12 21:09

import consultation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_alter_consultation_patient_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient_dob',
            field=models.DateField(validators=[consultation.models.validate_date_of_birth]),
        ),
    ]
